In [24]:
import yfinance as yf
import pandas as pd
import numpy as np
import random
import pickle
from sklearn.cluster import KMeans 

In [2]:
industry_stocks = {'Materials': ['BHP.AX',
  'FMG.AX',
  'RIO.AX',
  'NCM.AX',
  'JHX.AX',
  'S32.AX',
  'AMC.AX',
  'NST.AX',
  'BSL.AX'],
 'Real Estate': ['GMG.AX', 'SCG.AX', 'MGR.AX', 'DXS.AX', 'SGP.AX'],
 'Financials': ['CBA.AX',
  'WBC.AX',
  'NAB.AX',
  'ANZ.AX',
  'MQG.AX',
  'QBE.AX',
  'ASX.AX',
  'SUN.AX',
  'IAG.AX'],
 'Industrials': ['TCL.AX', 'SYD.AX', 'BXB.AX', 'REH.AX', 'AIA.AX'],
 'Health Care': ['CSL.AX', 'SHL.AX', 'FPH.AX', 'COH.AX', 'RHC.AX', 'RMD.AX'],
 'Information Technology': ['APT.AX', 'XRO.AX', 'CPU.AX']}

In [3]:
stock_list =[]
for ind in industry_stocks.values():
    stock_list.extend(ind)

In [4]:
data = yf.download(  # or pdr.get_data_yahoo(...
        # tickers list or string as well
        tickers = stock_list,

        # use "period" instead of start/end
        # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
        # (optional, default is '1mo')
        period = "5y",

        # fetch data by interval (including intraday if period < 60 days)
        # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
        # (optional, default is '1d')
        interval = "1d",

        # group by ticker (to access via data['SPY'])
        # (optional, default is 'column')
        group_by = 'ticker',

        # adjust all OHLC automatically
        # (optional, default is False)
        auto_adjust = True,

        # download pre/post regular market hours data
        # (optional, default is False)
        prepost = True,

        # use threads for mass downloading? (True/False/Integer)
        # (optional, default is True)
        threads = True,

        # proxy URL scheme use use when downloading?
        # (optional, default is None)
        proxy = None
    )

[*********************100%***********************]  37 of 37 completed


In [5]:
 data#.loc["2016":"2021"]

FPH.AX                                                XRO.AX  \
                 Open       High        Low      Close   Volume        Open   
Date                                                                          
2016-06-10   9.389770   9.417523   9.325013   9.343515   183959   18.670000   
2016-06-14   9.112240   9.130742   8.908718   8.982726   354221   18.350000   
2016-06-15   8.871715   9.223254   8.871715   9.158496   339734   17.620001   
2016-06-16   9.200988   9.313081   9.200988   9.285057   710184   17.870001   
2016-06-17   9.331763   9.341104   9.229011   9.303740   282202   18.200001   
...               ...        ...        ...        ...      ...         ...   
2021-06-04  27.150000  27.379999  27.000000  27.230000  1078576  128.589996   
2021-06-07  27.219999  27.610001  27.180000  27.600000   473300  129.789993   
2021-06-08  27.600000  27.620001  27.020000  27.350000  1222138  130.520004   
2021-06-09  27.260000  27.730000  27.160000  27.299999   806659  130.479996   
2021-06-10  27.299999  27.610001  27.120001  27.250000   550751  130.660004   

                                                        ...    IAG.AX  \
                  High         Low       Close  Volume  ...      Open   
Date                                                    ...             
2016-06-10   18.799999   18.500000   18.690001   42482  ...  4.643825   
2016-06-14   18.350000   17.575001   17.629999  352964  ...  4.578991   
2016-06-15   18.150000   17.400000   17.620001   33971  ...  4.562781   
2016-06-16   18.500000   17.870001   18.280001  102305  ...  4.546572   
2016-06-17   18.459999   18.010000   18.150000   30676  ...  4.546572   
...                ...         ...         ...     ...  ...       ...   
2021-06-04  130.320007  127.930000  129.410004  446762  ...  5.140000   
2021-06-07  130.449997  129.009995  130.149994  328626  ...  5.270000   
2021-06-08  132.009995  129.729996  132.009995  315151  ...  5.230000   
2021-06-09  132.169998  128.899994  129.279999  346768  ...  5.250000   
2021-06-10  133.559998  129.820007  133.539993  347317  ...  5.220000   

                                                      SHL.AX             \
                High       Low     Close   Volume       Open       High   
Date                                                                      
2016-06-10  4.724869  4.643825  4.676243  3071717  18.263859  18.562428   
2016-06-14  4.619512  4.562782  4.603304  5211182  18.101779  18.391817   
2016-06-15  4.570885  4.489841  4.489841  6329415  18.152962  18.366226   
2016-06-16  4.546572  4.489841  4.489841  7338575  18.280920  18.323572   
2016-06-17  4.635721  4.514155  4.603304  6588265  18.042066  18.118841   
...              ...       ...       ...      ...        ...        ...   
2021-06-04  5.240000  5.110000  5.230000  6502427  34.540001  35.369999   
2021-06-07  5.280000  5.190000  5.240000  3606613  35.680000  35.880001   
2021-06-08  5.290000  5.200000  5.250000  4817867  35.310001  35.759998   
2021-06-09  5.310000  5.210000  5.220000  3986834  35.500000  35.810001   
2021-06-10  5.280000  5.200000  5.230000  2077321  35.980000  36.150002   

                                           
                  Low      Close   Volume  
Date                                       
2016-06-10  18.042065  18.562428  1110712  
2016-06-14  18.067657  18.246798  1360039  
2016-06-15  18.076188  18.280920  1113689  
2016-06-16  17.871455  17.965290  1412868  
2016-06-17  17.722171  17.837334  1277983  
...               ...        ...      ...  
2021-06-04  34.529999  35.160000  1163534  
2021-06-07  35.139999  35.270000   782790  
2021-06-08  35.160000  35.520000   900888  
2021-06-09  35.330002  35.630001   961113  
2021-06-10  35.700001  35.810001   645057  

[1267 rows x 185 columns]

In [6]:
# stock like Afterpay lists later but may provide relevant value ( 5 year data used as well)
data_right = data.loc["2016":"2021"]

In [7]:
data_right.isna().sum()

FPH.AX  Open      0
        High      0
        Low       0
        Close     0
        Volume    0
                 ..
SHL.AX  Open      0
        High      0
        Low       0
        Close     0
        Volume    0
Length: 185, dtype: int64

In [8]:
stocks_close= pd.DataFrame(columns=stock_list)
for stock in stock_list:
    stocks_close[stock] = data_right[stock]['Close']
    


In [9]:
stocks_close = stocks_close[~stocks_close["APT.AX"].isna()]

In [10]:
stocks_close.isna().sum()

BHP.AX    0
FMG.AX    0
RIO.AX    0
NCM.AX    0
JHX.AX    0
S32.AX    0
AMC.AX    0
NST.AX    0
BSL.AX    0
GMG.AX    0
SCG.AX    0
MGR.AX    0
DXS.AX    0
SGP.AX    0
CBA.AX    0
WBC.AX    0
NAB.AX    0
ANZ.AX    0
MQG.AX    0
QBE.AX    0
ASX.AX    0
SUN.AX    0
IAG.AX    0
TCL.AX    0
SYD.AX    0
BXB.AX    0
REH.AX    0
AIA.AX    0
CSL.AX    0
SHL.AX    0
FPH.AX    0
COH.AX    0
RHC.AX    0
RMD.AX    0
APT.AX    0
XRO.AX    0
CPU.AX    0
dtype: int64

In [11]:
stocks_close

BHP.AX     FMG.AX      RIO.AX     NCM.AX     JHX.AX    S32.AX  \
Date                                                                           
2017-06-29  18.447258   3.465730   52.555302  19.788643  19.647369  2.492296   
2017-06-30  18.290127   3.472382   52.455811  19.244528  19.124935  2.420055   
2017-07-03  18.250843   3.498990   52.729408  19.120436  18.658474  2.420055   
2017-07-04  18.667244   3.498990   53.143948  18.948608  18.891703  2.465206   
2017-07-05  18.973648   3.552207   54.055935  18.872238  18.574509  2.492296   
...               ...        ...         ...        ...        ...       ...   
2021-06-04  48.750000  22.969999  124.620003  27.450001  42.950001  3.040000   
2021-06-07  48.849998  22.650000  125.330002  27.600000  43.099998  3.000000   
2021-06-08  48.380001  22.420000  124.160004  27.690001  43.520000  2.980000   
2021-06-09  48.669998  22.650000  124.800003  27.500000  43.509998  2.990000   
2021-06-10  48.310001  22.799999  125.089996  27.520000  44.360001  2.985000   

               AMC.AX     NST.AX     BSL.AX     GMG.AX  ...    AIA.AX  \
Date                                                    ...             
2017-06-29  13.810412   4.550181  12.773681   7.481699  ...  6.210143   
2017-06-30  13.543057   4.465570  12.715925   7.242431  ...  6.146589   
2017-07-03  13.401028   4.446767  12.985451   7.168810  ...  6.155669   
2017-07-04  13.651670   4.362157  13.274232   7.297647  ...  6.146589   
2017-07-05  13.685087   4.315151  13.389742   7.270039  ...  6.164748   
...               ...        ...        ...        ...  ...       ...   
2021-06-04  15.460000  10.910000  22.450001  20.160000  ...  7.140000   
2021-06-07  15.550000  10.930000  22.459999  20.530001  ...  7.130000   
2021-06-08  15.530000  11.050000  22.600000  20.389999  ...  7.110000   
2021-06-09  15.510000  10.900000  22.320000  20.250000  ...  7.200000   
2021-06-10  15.650000  11.030000  22.105000  20.670000  ...  7.160000   

                CSL.AX     SHL.AX     FPH.AX      COH.AX     RHC.AX  \
Date                                                                  
2017-06-29  135.642593  21.703848  10.597006  151.108536  70.006866   
2017-06-30  131.785370  21.385973  10.358333  146.893982  68.091789   
2017-07-03  129.150238  21.041609  10.148301  144.068558  67.518188   
2017-07-04  130.305450  21.438951  10.138756  145.240311  68.397087   
2017-07-05  128.892441  20.608942   9.976459  144.512695  67.897499   
...                ...        ...        ...         ...        ...   
2021-06-04  291.369995  35.160000  27.230000  228.850006  62.910000   
2021-06-07  292.570007  35.270000  27.600000  230.199997  62.070000   
2021-06-08  295.190002  35.520000  27.350000  232.750000  62.279999   
2021-06-09  294.109985  35.630001  27.299999  234.550003  63.490002   
2021-06-10  295.869995  35.810001  27.250000  234.919998  63.185001   

               RMD.AX     APT.AX      XRO.AX     CPU.AX  
Date                                                     
2017-06-29   9.910036   2.700000   24.650000  13.013454  
2017-06-30   9.792988   2.950000   24.190001  12.690361  
2017-07-03   9.812496   3.000000   24.000000  12.807034  
2017-07-04   9.851512   3.000000   24.200001  12.986528  
2017-07-05   9.871020   3.180000   24.480000  13.004478  
...               ...        ...         ...        ...  
2021-06-04  26.840000  94.480003  129.410004  16.250000  
2021-06-07  26.850000  96.379997  130.149994  16.110001  
2021-06-08  26.930000  97.199997  132.009995  16.180000  
2021-06-09  27.120001  98.839996  129.279999  16.129999  
2021-06-10  28.250000  99.809998  133.539993  16.209999  

[1002 rows x 37 columns]

In [12]:
stocks_close.columns.to_list()

['BHP.AX',
 'FMG.AX',
 'RIO.AX',
 'NCM.AX',
 'JHX.AX',
 'S32.AX',
 'AMC.AX',
 'NST.AX',
 'BSL.AX',
 'GMG.AX',
 'SCG.AX',
 'MGR.AX',
 'DXS.AX',
 'SGP.AX',
 'CBA.AX',
 'WBC.AX',
 'NAB.AX',
 'ANZ.AX',
 'MQG.AX',
 'QBE.AX',
 'ASX.AX',
 'SUN.AX',
 'IAG.AX',
 'TCL.AX',
 'SYD.AX',
 'BXB.AX',
 'REH.AX',
 'AIA.AX',
 'CSL.AX',
 'SHL.AX',
 'FPH.AX',
 'COH.AX',
 'RHC.AX',
 'RMD.AX',
 'APT.AX',
 'XRO.AX',
 'CPU.AX']

In [13]:
#store stock prices as an array
assetLabels = stocks_close.columns.to_list()
arStockPrices = np.asarray(stocks_close)
[rows, cols]= arStockPrices.shape
print(rows, cols)
print(arStockPrices)


1002 37
[[ 18.447258     3.46572995  52.55530167 ...   2.70000005  24.64999962
   13.01345444]
 [ 18.2901268    3.47238183  52.45581055 ...   2.95000005  24.19000053
   12.69036102]
 [ 18.25084305   3.4989903   52.72940826 ...   3.          24.
   12.80703449]
 ...
 [ 48.38000107  22.42000008 124.16000366 ...  97.19999695 132.00999451
   16.18000031]
 [ 48.66999817  22.64999962 124.80000305 ...  98.83999634 129.27999878
   16.12999916]
 [ 48.31000137  22.79999924 125.08999634 ...  99.80999756 133.53999329
   16.20999908]]


In [14]:
#function for Stock Returns computing 
def StockReturnsComputing(StockPrice, Rows, Columns):
    
    import numpy as np
    
    StockReturn = np.zeros([Rows-1, Columns])
    for j in range(Columns):  # j: Assets
        for i in range(Rows-1):     #i: Daily Prices
            StockReturn[i,j]=((StockPrice[i+1, j]-StockPrice[i,j])/StockPrice[i,j])

    return StockReturn


In [15]:
#compute daily returns of all stocks in the mini universe
# get back array of daily returns
arReturns = StockReturnsComputing(arStockPrices, rows, cols)
print('Size of the array of daily returns of stocks:\n', arReturns.shape)
print('Array of daily returns of stocks\n',  arReturns)

Size of the array of daily returns of stocks:
 (1001, 37)
Array of daily returns of stocks
 [[-0.00851786  0.00191933 -0.00189307 ...  0.09259259 -0.01866122
  -0.02482764]
 [-0.00214781  0.00766289  0.00521578 ...  0.01694914 -0.00785451
   0.00919387]
 [ 0.02281543  0.          0.00786163 ...  0.          0.00833337
   0.01401526]
 ...
 [-0.00962124 -0.01015451 -0.00933534 ...  0.00850799  0.01429121
   0.00434511]
 [ 0.00599415  0.01025868  0.00515463 ...  0.01687242 -0.02068022
  -0.00309031]
 [-0.00739669  0.0066225   0.00232366 ...  0.00981385  0.03295169
   0.0049597 ]]


In [16]:
#compute mean returns and variance covariance matrix of returns
meanReturns = np.mean(arReturns, axis = 0)
print('Mean returns:\n', meanReturns)
covReturns = np.cov(arReturns, rowvar=False)
#set precision for printing results
np.set_printoptions(precision=5, suppress = True)
print('Size of Variance-Covariance matrix of returns:\n', covReturns.shape)
print('Variance-Covariance matrix of returns:\n', covReturns)

Mean returns:
 [1.11085217e-03 2.18866856e-03 1.00118955e-03 5.24745781e-04
 1.04421194e-03 4.57543686e-04 2.11338359e-04 1.29701766e-03
 8.78173763e-04 1.16989338e-03 8.62549640e-05 6.47512562e-04
 4.05860816e-04 5.31168164e-04 5.08755347e-04 1.95043672e-04
 2.43481519e-04 3.50323848e-04 8.52284972e-04 2.72903403e-04
 5.32775397e-04 3.40881127e-05 2.02492628e-05 4.52099789e-04
 1.01915474e-04 3.39513916e-04 1.21980347e-03 3.12672811e-04
 9.24719571e-04 6.14593444e-04 1.11806636e-03 6.42956139e-04
 5.89141436e-05 1.21256049e-03 4.72674418e-03 1.95168886e-03
 3.80036126e-04]
Size of Variance-Covariance matrix of returns:
 (37, 37)
Variance-Covariance matrix of returns:
 [[0.0003  0.00028 0.00023 ... 0.00021 0.00011 0.00014]
 [0.00028 0.00061 0.00029 ... 0.00022 0.00013 0.00012]
 [0.00023 0.00029 0.00027 ... 0.0002  0.00009 0.0001 ]
 ...
 [0.00021 0.00022 0.0002  ... 0.00225 0.0004  0.00032]
 [0.00011 0.00013 0.00009 ... 0.0004  0.00052 0.00016]
 [0.00014 0.00012 0.0001  ... 0.00032 0.00

*Prepare parameters for k-means clustering



In [17]:
#prepare asset parameters for k-means clustering
#reshape for concatenation
meanReturns = meanReturns.reshape(len(meanReturns),1)
assetParameters = np.concatenate([meanReturns, covReturns], axis = 1)
print('Size of the asset parameters for clustering:\n', assetParameters.shape)
print('Asset parameters for clustering:\n', assetParameters)

Size of the asset parameters for clustering:
 (37, 38)
Asset parameters for clustering:
 [[0.00111 0.0003  0.00028 ... 0.00021 0.00011 0.00014]
 [0.00219 0.00028 0.00061 ... 0.00022 0.00013 0.00012]
 [0.001   0.00023 0.00029 ... 0.0002  0.00009 0.0001 ]
 ...
 [0.00473 0.00021 0.00022 ... 0.00225 0.0004  0.00032]
 [0.00195 0.00011 0.00013 ... 0.0004  0.00052 0.00016]
 [0.00038 0.00014 0.00012 ... 0.00032 0.00016 0.00032]]


In [18]:
#kmeans clustering of assets using the characteristic vector of 
# mean return and variance-covariance vector of returns
# random state to minimise impact centroid changes 
clusters=8
assetsCluster= KMeans(algorithm='auto',  max_iter=600, n_clusters=clusters,random_state = 1)
print('Clustering of assets completed!') 
assetsCluster.fit(assetParameters)
centroids = assetsCluster.cluster_centers_
labels = assetsCluster.labels_

print('Centroids:\n', centroids)
print('Labels:\n', labels)

Clustering of assets completed!
Centroids:
 [[ 0.00042  0.0001   0.00007  0.00008  0.00005  0.00021  0.00016  0.00008
   0.00002  0.00015  0.00021  0.00039  0.00036  0.00023  0.00039  0.00016
   0.0002   0.00021  0.00021  0.00022  0.0002   0.00008  0.00019  0.00012
   0.00017  0.00019  0.00008  0.00011  0.00018  0.00009  0.00009 -0.00001
   0.00011  0.00012  0.00003  0.00036  0.00013  0.00015]
 [ 0.00103  0.00016  0.00015  0.00014  0.00005  0.00019  0.00019  0.00007
   0.00005  0.00023  0.00014  0.00014  0.00014  0.0001   0.00016  0.00012
   0.00014  0.00013  0.00015  0.00018  0.00015  0.00009  0.00014  0.00011
   0.00011  0.0001   0.00008  0.00011  0.0001   0.00012  0.00008  0.00004
   0.00012  0.00011  0.00007  0.00028  0.00014  0.00013]
 [ 0.00473  0.00021  0.00022  0.0002   0.00014  0.00036  0.00029  0.00014
   0.0001   0.00037  0.0003   0.00034  0.00034  0.00021  0.00041  0.00023
   0.00029  0.0003   0.00032  0.00039  0.00031  0.00017  0.00025  0.00018
   0.00029  0.00022  0.00015

In [19]:
#fixing asset labels to cluster points
print('Stocks in each of the clusters:\n',)
assets = np.array(assetLabels)
cluster_kme = {}
for i in range(clusters):
    print('Cluster', i+1)
    clt  = np.where(labels == i)
    assetsCluster = assets[clt]
    cluster_kme[f'Cluster, {i+1}'] = assets[clt]
    print(assetsCluster)
    

Stocks in each of the clusters:

Cluster 1
['SCG.AX' 'MGR.AX' 'SGP.AX']
Cluster 2
['BHP.AX' 'RIO.AX' 'JHX.AX' 'BSL.AX' 'GMG.AX' 'MQG.AX' 'REH.AX' 'CSL.AX']
Cluster 3
['APT.AX']
Cluster 4
['NCM.AX' 'AMC.AX' 'ASX.AX' 'BXB.AX' 'SHL.AX' 'COH.AX']
Cluster 5
['S32.AX' 'DXS.AX' 'CBA.AX' 'WBC.AX' 'NAB.AX' 'ANZ.AX' 'QBE.AX' 'SUN.AX'
 'IAG.AX' 'TCL.AX' 'SYD.AX' 'AIA.AX' 'RHC.AX' 'CPU.AX']
Cluster 6
['NST.AX']
Cluster 7
['FMG.AX' 'XRO.AX']
Cluster 8
['FPH.AX' 'RMD.AX']


In [20]:
cluster_kme 

{'Cluster, 1': array(['SCG.AX', 'MGR.AX', 'SGP.AX'], dtype='<U6'),
 'Cluster, 2': array(['BHP.AX', 'RIO.AX', 'JHX.AX', 'BSL.AX', 'GMG.AX', 'MQG.AX',
        'REH.AX', 'CSL.AX'], dtype='<U6'),
 'Cluster, 3': array(['APT.AX'], dtype='<U6'),
 'Cluster, 4': array(['NCM.AX', 'AMC.AX', 'ASX.AX', 'BXB.AX', 'SHL.AX', 'COH.AX'],
       dtype='<U6'),
 'Cluster, 5': array(['S32.AX', 'DXS.AX', 'CBA.AX', 'WBC.AX', 'NAB.AX', 'ANZ.AX',
        'QBE.AX', 'SUN.AX', 'IAG.AX', 'TCL.AX', 'SYD.AX', 'AIA.AX',
        'RHC.AX', 'CPU.AX'], dtype='<U6'),
 'Cluster, 6': array(['NST.AX'], dtype='<U6'),
 'Cluster, 7': array(['FMG.AX', 'XRO.AX'], dtype='<U6'),
 'Cluster, 8': array(['FPH.AX', 'RMD.AX'], dtype='<U6')}

To avoid risk, select one from each cluster $k$-portfolios 

In [21]:
selected_stocks_cluster=[]
for cluster, stocks in cluster_kme.items():
   rand_choice= random.randint(0,len(stocks)-1)
   selected_stocks_cluster.append(stocks[rand_choice])



In [22]:
selected_stocks_cluster

['MGR.AX',
 'JHX.AX',
 'APT.AX',
 'ASX.AX',
 'RHC.AX',
 'NST.AX',
 'XRO.AX',
 'RMD.AX']

In [25]:
with open('./data/pickles/selected_stocks_cluster.pickle', 'wb') as handle:
    pickle.dump(selected_stocks_cluster, handle, protocol=pickle.HIGHEST_PROTOCOL)